type ENV = {
  REACT_APP_INFURA_API_KEY?: string;
  REACT_APP_API_SERVER: string;
  REACT_APP_ALT_URL?: string;
  REACT_APP_TARGET_NETWORK_KLAY: number;
  REACT_APP_TARGET_NETWORK_ETH: number;
  REACT_APP_TARGET_NETWORK_BNB: number;
  REACT_APP_TARGET_NETWORK_SOL?: number;
  REACT_APP_TARGET_NETWORK_MSG?: string;
  REACT_APP_MBOX_FEE?: number;
  REACT_APP_TREASURY?: string;
};

const development: ENV = {
  REACT_APP_API_SERVER: 'http://127.0.0.1:5001',
  // REACT_APP_API_SERVER: 'https://dev.nftapi.talken.io',
  REACT_APP_TARGET_NETWORK_KLAY: 1001, // TMP
  REACT_APP_TARGET_NETWORK_ETH: 3,
  REACT_APP_TARGET_NETWORK_BNB: 97,
  // REACT_APP_TARGET_NETWORK_SOL:
  REACT_APP_TREASURY: '0x22ae69E7b2DE09548B6b15b5D92D2b04De5592d9',
};

const staging: ENV = {
  // REACT_APP_API_SERVER: 'http://127.0.0.1:5001',
  REACT_APP_API_SERVER: 'https://dev.nftapi.talken.io',
  REACT_APP_TARGET_NETWORK_KLAY: 1001, // TMP
  REACT_APP_TARGET_NETWORK_ETH: 3,
  REACT_APP_TARGET_NETWORK_BNB: 97,
  // REACT_APP_TARGET_NETWORK_SOL:
  REACT_APP_TREASURY: '0x22ae69E7b2DE09548B6b15b5D92D2b04De5592d9',
};

const production: ENV = {
  REACT_APP_API_SERVER: 'https://nftapi.talken.io',
  REACT_APP_TARGET_NETWORK_KLAY: 8217, // TMP
  REACT_APP_TARGET_NETWORK_ETH: 1,
  REACT_APP_TARGET_NETWORK_BNB: 56,
  // REACT_APP_TARGET_NETWORK_SOL:
  REACT_APP_TREASURY: '0x1424C82f9Cb4BeeaD8294087aa731A0c4FB2767D',
};

const env =
  process.env.REACT_APP_PHASE === 'staging'
    ? staging
    : process.env.REACT_APP_PHASE === 'production'
    ? production
    : development;

export default env;
